from backend.core.model_registry import (
    BASE_YOLO_MODEL_PATH,
    CUSTOM_YOLO_MODEL_PATH,
    FACE_EMBEDDINGS_PATH,
    LEGACY_BASE_YOLO_MODEL_PATH,
    LEGACY_CUSTOM_YOLO_MODEL_PATH,
)

MODEL_PATH = CUSTOM_YOLO_MODEL_PATH
TEMPORAL_WINDOW_FRAMES = 15
SUSPICIOUS_FRAME_THRESHOLD = 10
